<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>AUModdedRegions</AssemblyName>
    <RootNamespace>AUModdedRegions</RootNamespace>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    
    <!-- Masque le warning NU1603 -->
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
    <!-- Packages Unity gérés par NuGet pour le build -->
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.16" PrivateAssets="all" IncludeAssets="compile" />
  </ItemGroup>

</Project>
