name: Build

on:
  push:

jobs:
  build:
    runs-on: raspberry-pi

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: AmongUsMod
          path: "**/bin/Release/**/*.dll"